config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users

  
  get 'profiles/new', to: 'profiles#new', as: 'profiles'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profiles/:id', to: 'profiles#update'
  post 'profiles/new', to: 'profiles#create'
  delete 'profiles/:id', to: 'profiles#destroy'


  get 'items', to: 'items#index', as: 'items'
  get 'items/new', to: 'items#new', as: 'new'
  get 'items/:id', to: 'items#show', as: 'item'
  post 'items/new', to: 'items#create'
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item'
  patch 'items/:id', to: 'items#update'
  get 'user/items', to: 'items#user_items', as: 'user_items'
  delete 'items/:id', to: 'items#destroy'

  get 'items/:item_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  put 'bookings/:id', to: 'bookings#update'
  post 'items/:item_id/bookings/new', to: 'bookings#create'
  delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
  get 'bookings', to: 'bookings#index', as: 'bookings'
  get 'bookings/:id', to: 'bookings#edit', as: 'edit_booking'

  
  # devise_for :users
  get 'pages/index'  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/views/partials/_booking_table.html.erb
<% if @bookings.length == 0 %>
<br></br>
  <p>You have no bookings. </p>
<%else%>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Booking ID</th>
        <th scope="col">Item</th>
        <th scope="col">Daily Fee</th>
        <th scope="col">Hire Date</th>
        <th scope="col">Return Date</th>
        <th scope="col">Duration (days) </th>
        <th scope="col">Total Fee </th>
      </tr>
    </thead>
    <% @bookings.each do |booking| %>
      <tbody>
        <tr>
          <td><%= booking.id %> </td>
          <td><%= link_to Item.find(booking.item_id).title, Item.find(booking.item_id) %> </td>
          <td>$<%= Item.find(booking.item_id).price %>0</td>
          <td><%= booking.start_date %> </td>
          <td><%= booking.end_date %> </td>
          <td><%= duration(booking) %></td>
          <td>$<%= total_fee(booking)  %>0</td>
          <td><%= link_to('Manage booking', edit_booking_path(booking), class: 'btn btn-primary me-2') %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>

app/views/partials/_item_form.html.erb
<style>

.mb-2 input{
    width: 100%!important;
    height: 2rem;
}

.mb-3 input{
    height: 6rem;
    width: 100%!important;
}

fieldset.mb-2-2{
  width: 100%!important;
}

</style>

<%= form_with(model: @item, data: {turbo: false}) do |f| %>
  <table class="table">
    <thead>
      
    </thead>
    <tbody>
      <tr>
        <th scope="row">Title:</th>
        <td>  
          <fieldset class="mb-2">
            <%= f.text_field :title %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Description:</th>
        <td>
          <fieldset class="mb-3">
            <%= f.text_field :description %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Category:</th>
        <td>  
          <fieldset class="mb-2-2">
            <%= f.collection_select :category_id, @categories, :id, :name %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Daily Fee:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.number_field :price %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Item Photo:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.file_field :image %>
          </fieldset>
        </td>
      </tr>
    </tbody>
  </table>
  <fieldset>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/partials/_listings.html.erb
<style>
  .py-5 {
      padding-left: 3rem;
      padding-right: 3rem;
  }

  .price {
    position: absolute;
    right: 1rem;
    bottom: -2rem;
  }


  div.card-body {
    position: absolute;
    width: 100%;
    bottom: 3rem;
    background-color: white;
    z-index: 10;

  }
</style>
<% if @items.length == 0 %>
  <br>
</br>
<p>You have no items listed.</p>
<% else %>
  <div class="album py-5 bg-light">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @items.each do |item| %>
        <div class="col">
          <div class="card" style='height: 25rem;'>
            <% if item.image.attached?%>
              <%= cl_image_tag item.image.key, :crop=>"pad", cloud_name: 'damonjohnson' %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to item.title, item %></h5>
              <p class="card-text"><%= item.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <p class="card-text"></p>
                </div>

                <large class="price">$<%= item.price %>0 / day</large>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/partials/_navbar.html copy.erb
<!DOCTYPE html>
<html lang="en">
  <html>
    <head>
      <header>
        <style>
        

        @import url('https://fonts.googleapis.com/css2?family=Akshar&display=swap');


          .navbar .nav-link {
            color:  #ff5600!important;
            font-family: 'Akshar', sans-serif;
            font-size: 1.3rem;
            margin-left: 0.5rem;
            margin-right: 0.5rem;

          }

          .navbar .nav-link:hover {
            color:  white!important;
          }

          .btn-nav {
            color:  #ff5600!important;
            background: transparent !important;
            border: none !important;
            font-family: 'Akshar', sans-serif;
            font-size: 1.3rem;
            padding-top: 1rem;
          }

          .btn-nav:hover {
            color:  white!important;
          }

          .nav-logo {
            padding-left: 1rem;
            padding-right: 1rem;
          }
          
          .nav_bar-toggler-icon {
            border: 3px solid #ff5600!important;
          }
        

          .navbar {
            background: #0d3d57!important;
            border-bottom: 6px solid #ff5600;
            height: 70px;
          }

          .navbar-text {
            margin-left: 0;
          }

          .navbar-collapse.collapse.show{
            background: #0d3d57!important;
            z-index: 10!important;
            border: 3px solid #ff5600;
          }


        </style>
      </head>
      <nav class="navbar navbar-expand-lg navbar-light bg-light"k>
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <%= image_tag 'https://res.cloudinary.com/damonjohnson/image/upload/v1652952698/logo_d6qmeu.png', class: "nav-logo", style: 'height:30px'%>
          </a> 
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'View listings', items_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Add Listing', new_path, class: 'nav-link' %>
              </li>
            </ul>
            <% if user_signed_in? && user_has_profile?  %>
              <span class="navbar-text">
                <%= link_to 'My Account',  profile_path(current_user.profile.id), class: 'nav-link' %>
              </span>
              <div class="navbar-text">
              <%= button_to 'Logout', destroy_user_session_path,  class: 'btn-nav', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out? " } } %>
            </div>
            <% elsif user_signed_in? %>
            <div class="navbar-text">
            </div>
            <% else %>
              <span class="navbar-text">
                <a class="nav-link" href="/users/sign_in" >Log in</a>
              </span>
              <span class="navbar-text">
                <a class="nav-link" href="/users/sign_up"'>Sign up</a>
              </span>
            <% end %>
          </div>
        </div>
      </nav>

app/views/partials/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
  <html>
    <head>
      <header>
        <style>
        

        @import url('https://fonts.googleapis.com/css2?family=Akshar&display=swap');


          .navbar .nav-link {
            color:  #ff5600!important;
            font-family: 'Akshar', sans-serif;
            font-size: 1.3rem;
            margin-left: 0.5rem;
            margin-right: 0.5rem;

          }

          .navbar .nav-item {
            margin-left: 0.5rem;
            margin-right: 0.5rem;
          }

          .navbar .nav-link:hover {
            color:  white!important;
          }

          .btn-nav {
            color:  #ff5600!important;
            background: transparent !important;
            border: none !important;
            font-family: 'Akshar', sans-serif;
            font-size: 1.3rem;
            padding-top: 1rem;
          }

          .btn-nav:hover {
            color:  white!important;
          }

          .nav-logo {
            padding-left: 1rem;
            padding-right: 1rem;
          }
          
          .nav_bar-toggler-icon {
            border: 3px solid #ff5600!important;
          }
        

          .navbar {
            background: #0d3d57!important;
            border-bottom: 6px solid #ff5600;
            height: 70px;
          }

          .nav-link#nav-li3 {
            margin-left: -0.1rem!important; 
            margin-top: -0.2rem!important;
          }

          .btn-nav#nav-li4 {
            margin-left: 0.5rem!important;
            margin-top: -0.3rem!important;
          }


          .navbar-collapse.collapse.show{
            background: #0d3d57!important;
            z-index: 10!important;
            border: 3px solid #ff5600;
          }


        </style>
      </head>
      <nav class="navbar navbar-expand-lg navbar-light bg-light"k>
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <%= image_tag 'https://res.cloudinary.com/damonjohnson/image/upload/v1652952698/logo_d6qmeu.png', class: "nav-logo", style: 'height:30px'%>
          </a> 
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'View listings', items_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Add listing', new_path, class: 'nav-link' %>
              </li>
            </ul>
            <% if user_signed_in? && user_has_profile?  %>
              <div class="navbar-text">
                <%= link_to 'My account',  profile_path(current_user.profile.id), id: 'nav-li3', class: 'nav-link' %>
              </div>
              <div class="navbar-text">
              <%= button_to 'Logout', destroy_user_session_path,  id: 'nav-li4', class: 'btn-nav', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out? " } } %>
            </div>
            <% elsif user_signed_in? %>
            <div class="navbar-text">
            </div>
            <% else %>
              <div class="navbar-text">
                <a class="nav-link" href="/users/sign_in" >Log in</a>
              </div>
              <div class="navbar-text">
                <a class="nav-link" href="/users/sign_up"'>Sign up</a>
              </div>
            <% end %>
          </div>
        </div>
      </nav>

app/views/partials/_profile_form.html.erb
<style>

.table {
    
}
.mb-2 input{
    width: 100%!important;
    height: 2rem;
}



</style>

<%= form_with(model: @profile, data: {turbo: false}) do |f| %>
  <table class="table">
    <thead>
    </thead>
    <tbody>
      <tr>
        <th scope="row">First name:</th>
        <td>  
          <fieldset class="mb-2">
            <%= f.text_field :first_name %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Last name:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.text_field :last_name %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">Address:</th>
        <td>  
          <fieldset class="mb-2">
            <%= f.text_field :address %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">City:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.text_field :city %>
          </fieldset>
        </td>
      </tr>
      <tr>
        <th scope="row">State:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.select :state, @states %>
          </fieldset>
        </td>
      </tr>
       <tr>
        <th scope="row">Postcode:</th>
        <td>
          <fieldset class="mb-2">
            <%= f.number_field :postcode %>
          </fieldset>
        </td>
      </tr>
    </tbody>
  </table>
  <fieldset>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/partials/_search.html.erb
<%= search_form_for @q do |f|  %>
  <div class="input-group">
    <%= f.search_field :title_or_category_name_or_description_cont, placeholder: "Search by item name or category", class: 'form-control' %>
  <%= f.submit "Search", class: "btn btn-primary"%>
<% end %>
</div>