config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users

  
  get 'profiles/new', to: 'profiles#new', as: 'profiles'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profiles/:id', to: 'profiles#update'
  post 'profiles/new', to: 'profiles#create'
  delete 'profiles/:id', to: 'profiles#destroy'


  get 'items', to: 'items#index', as: 'items'
  get 'items/new', to: 'items#new', as: 'new'
  get 'items/:id', to: 'items#show', as: 'item'
  post 'items/new', to: 'items#create'
  get 'items/:id/edit', to: 'items#edit', as: 'edit_item'
  patch 'items/:id', to: 'items#update'
  get 'user/items', to: 'items#user_items', as: 'user_items'
  delete 'items/:id', to: 'items#destroy'

  get 'items/:item_id/bookings/new', to: 'bookings#new', as: 'new_booking'
  put 'bookings/:id', to: 'bookings#update'
  post 'items/:item_id/bookings/new', to: 'bookings#create'
  delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
  get 'bookings', to: 'bookings#index', as: 'bookings'
  get 'bookings/:id', to: 'bookings#edit', as: 'edit_booking'

  
  # devise_for :users
  get 'pages/index'  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/item.rb
class Item < ApplicationRecord
    resourcify
    belongs_to :category
    belongs_to :user
    has_many :bookings

    has_one_attached :image
    
    validates :title, :description, :category, :price, :image, presence: true
    validates :price, comparison: { greater_than: 0}
end 
 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :check_auth]
  before_action :check_auth, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :update, :create]


 
  
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
    
  end



  def show
  end

  def new

  end

  # Leverages devise current_user method to create item where item is controllers
  def create
    begin
    @item = current_user.items.new(item_params)
    @item.save!
    # User is assigned item_owner scoped to item for item policy
    current_user.add_role :item_owner, @item
    flash[:notice] = "Item listed. Thanks for sharing."
    redirect_to @item
    rescue
    flash[:alert] = @item.errors.full_messages.join('.  ')
    redirect_to new_path
    end
  end

  def edit
  end


  def update 
    begin
    @item.update!(require_params)
    flash[:notice] = "Successfully updated"   
    redirect_to item_path(@item)
    rescue
    flash[:alert] = @item.errors.full_messages.join('.  ')   
    render 'edit'
    end
  end

  def destroy  
    # @item.image.purge
    @item.destroy
    redirect_to items_path
  end


  private

  # Checks if current user is creator of @item
  def check_auth
   authorize @item
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def get_categories
    @categories = Category.all
  end

# Does not require item id. Used for creating new items
  def item_params
    return params.permit(:title, :description, :price, :user_id, :category_id, :image)
  end

# Returns parameters for current @item, requires item id
   def require_params
    return params.require(:item).permit(:title, :description, :price, :user_id, :category_id, :image)
  end

  # Establishes set of categories for item creation and searching. Needs to be item controller as it is called before creation of items.
  def set_categories
    @categories = Category.create([{name: "4WD"},{name: "Campervan"},{name: "Caravan"},{name: "Boat"},{name: "Kayak / Canoe"},{name: "Bike"},{name: "Camping Equipment"},{name: "Surf"},{name: "Snow"},{name: 'Other'}])
  end

end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= render 'partials/item_form' %>

app/views/items/index.html.erb
<h1>Available to hire</h1>
<br></br>
<%= render 'partials/search' %>

<%= sort_link(@q, :price, "Sort by price", default_order: :asc) %>
<%= render 'partials/listings'%>

app/views/items/new.html copy.erb
<h1>Add an item</h1>
<br>
<%= form_with(model: @item, data: {turbo: false}) do |f| %>
  <fieldset class="mb-2">
    <%= f.label :title %>:
    <%= f.text_field :title %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :description %>:
    <%= f.text_field :description %>
  </fieldset>
  <fieldset class="mb-2">
  <%= f.label :category_id %>:
    <%= f.collection_select :category_id, @categories, :id, :name %>
  </fieldset>
   <fieldset class="mb-2">
    <%= f.label :price %>:
    <%= f.number_field :price %>
  </fieldset>
  <fieldset class="mb-2">
    <%= f.label :image %>:
    <%= f.file_field :image %>
  </fieldset>
  <fieldset>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/items/new.html.erb
<h1>Add listing</h1>
<br>

<%= render 'partials/item_form' %>

app/views/items/show.html.erb
<style>

.btn {
  height: 40px;
} 
</style>


<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold"><%= @item.title %></h1>

<br>
</br>
<% if @item.image.attached?%>
  <%= cl_image_tag @item.image.key, crop: :scale, width: 450, cloud_name: 'damonjohnson' %>
<% end %>
<br>
</br>

<table class="table">
  <thead> 
    <tr>
      <th scope="col">Item ID</th>
      <th scope="col">Item Name</th>
      <th scope="col">Category</th>
      <th scope="col">Description</th>
      <th scope="col">Daily Fee</th>
      <th scope="col">Owner</th>
    </tr>
  </thead>

  <tbody>
    <tr>    
      <td><%= @item.id %> </td>
      <td><%= @item.title %> </td>
      <td><%= @item.category.name %></td>
      <td><%= @item.description %> </td>
      <td>$<%= @item.price %>0</td>
      <td><%= @item.user.email %></td>
    </tr>
  </tbody>
</table>
<div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
  <%= link_to('Book item', new_booking_path(@item), class: 'btn btn-primary me-2') if @item.user_id != current_user.id %>
  <%= link_to('Edit Item', edit_item_path(@item), class: 'btn btn-warning me-2') if @item.user_id == current_user.id %>
  <%= button_to('Delete', @item, class: 'btn btn-danger', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete '#{@item.title}' ?" } }) if @item.user_id == current_user.id %>
</div>

app/views/items/update.html.erb
<h1>Itemx#update</h1>
<p>Find me in app/views/item/update.html.erb</p>

app/views/items/user_items.html.erb
<h1>My Listings</h1>

<div class="album py-5 bg-light">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @user_items.each do |item| %>
      <div class="col">
        <div class="card h-100">
          <img src="https://picsum.photos/500/200" class="card-img-top" alt="<%= item.title %>">
          <div class="card-body">
            <h5 class="card-title"><%= link_to item.title, item %></h5>
            <p class="card-text"><%= item.description %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Delete</button>
              </div>
              <large class="text">$<%= item.price %>0 / day</large>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>